name: CI-CD GitOps

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd-springboot:${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd-springboot:latest